spring.application.name: FAF Galactic War server
spring:
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  oauth2:
    resource:
      filter-order: 3
camunda:
  bpm:
    application:
      isDeleteUponUndeploy: false
      isScanForProcessDefinitions: false
      isDeployChangedOnly: true
      isResumePreviousVersions: true
      resumePreviousBy: a value
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false
logging:
  level:
    com.faforever.gw: debug
server:
  port: 8014

#camunda.bpm.auto-deployment-enabled: false