faf-gw:
  jwt:
    secret: secret
  lobby:
    connection-string: ${faf-gw.lobby.protocol}://${faf-gw.lobby.host}:${faf-gw.lobby.port}/ws
    protocol: ws
    host: localhost
    port: 8012
spring:
  datasource:
    url: jdbc:h2:mem:camunda
    username: sa
    password:
    driverClassName: org.h2.Driver
#    url: jdbc:postgresql://${DATABASE_ADDRESS:127.0.0.1}:5432/${DATABASE_NAME:faf-gw}?useSSL=false
#    name: faf-db-pg
#    username: ${DATABASE_USERNAME:postgres}
#    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
logging:
  level:
    com.faforever.gw: debug
#    org.springframework: debug
    org.springframework.web.socket: info